name: Build and Test

on:
  push:
    branches:
      - develop  # Adjust if you want to trigger on different branches
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Configure
        run: cmake -S . -B build -G "Visual Studio 17 2022"

      - name: Build Debug
        run: cmake --build build --config Debug

      - name: Build Release
        run: cmake --build build --config Release

      - name: Run Unit Tests Debug
        run: build/bin/Debug/UnitTests.exe

      - name: Run Unit Tests Release
        run: build/bin/Release/UnitTests.exe
